[package]
org = "ballerinax"
name = "apim_catalog_tests"
version = "@toml.version@"

[[dependency]]
org = "test"
name = "helper_services"
version = "0.1.0"
repository="local"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina"
artifactId = "wso2.apim.catalog-native"
version = "@toml.version@"
path = "../native/build/libs/wso2.apim.catalog-native-@project.version@.jar"
