[package]
org = "sasindu"
name = "wso2.apim.catalog"
version = "0.1.0"
distribution = "2201.9.0-SNAPSHOT"

[[platform.java17.dependency]]
groupId = "io.ballerina"
artifactId = "wso2.apim.catalog-native"
version = "@toml.version@"
path = "../native/build/libs/wso2.apim.catalog-native-@project.version@.jar"
