[plugin]
id = "wso2.apim.catalog-compiler-plugin"
class = "io.ballerina.wso2.apim.catalog.ServiceCatalogCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/wso2.apim.catalog-compiler-plugin-0.1.0.jar"

[[dependency]]
path = "lib/ballerina-to-openapi-1.9.0-20240404-131600-58fb575.jar"