[package]
org = "admin"
name = "sample_project_1"
version = "0.1.0"
distribution = "2201.9.0-20240403-192700-6cd56dab"

[[dependency]]
org = "sasindu"
name = "wso2.apim.catalog"
version = "0.1.0"
repository="local"
